# Generated by Django 4.2.2 on 2023-06-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_added_customer_index_tablename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_828de0_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
