# Generated by Django 4.2.2 on 2023-06-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_store_custo_last_na_828de0_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membersbip',
            new_name='membership',
        ),
    ]
